"""
AlphaDesk — Base Strategy
Abstract class for all trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

import pandas as pd


class Signal(Enum):
    STRONG_BUY = 2
    BUY = 1
    NEUTRAL = 0
    SELL = -1
    STRONG_SELL = -2


@dataclass
class TradeSignal:
    """A trading signal generated by a strategy."""
    symbol: str
    instrument_id: int
    signal: Signal
    strategy_name: str
    confidence: float          # 0.0 to 1.0
    entry_price: float
    stop_loss: float
    take_profit: float
    suggested_size_pct: float  # % of allocated capital
    metadata: dict = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate risk/reward ratio."""
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        return reward / risk if risk > 0 else 0

    @property
    def direction(self) -> str:
        return "Buy" if self.signal.value > 0 else "Sell"


class BaseStrategy(ABC):
    """Abstract base for all strategies."""

    def __init__(self, name: str, allocation_pct: float, max_positions: int = 5):
        self.name = name
        self.allocation_pct = allocation_pct
        self.max_positions = max_positions
        self.active_signals: List[TradeSignal] = []
        self._last_run: Optional[datetime] = None

    @abstractmethod
    async def generate_signals(self, data_engine, current_positions: List[dict]) -> List[TradeSignal]:
        """Generate trading signals based on market data.

        Args:
            data_engine: DataEngine instance for fetching data
            current_positions: Currently open positions for this strategy

        Returns:
            List of TradeSignal objects
        """
        pass

    @abstractmethod
    def should_exit(self, position: dict, current_data: pd.DataFrame) -> Optional[TradeSignal]:
        """Check if an existing position should be closed.

        Returns exit signal if position should close, None otherwise.
        """
        pass

    def filter_signals(self, signals: List[TradeSignal],
                        min_confidence: float = 0.6,
                        min_rr_ratio: float = 1.5) -> List[TradeSignal]:
        """Filter signals by quality thresholds."""
        filtered = [
            s for s in signals
            if s.confidence >= min_confidence
            and s.risk_reward_ratio >= min_rr_ratio
        ]
        # Sort by confidence * risk_reward
        filtered.sort(key=lambda s: s.confidence * s.risk_reward_ratio, reverse=True)
        # Cap at max positions
        return filtered[:self.max_positions]

    def log_signals(self, signals: List[TradeSignal]):
        """Log generated signals for audit trail."""
        import logging
        logger = logging.getLogger(f"alphadesk.strategy.{self.name}")
        for s in signals:
            logger.info(
                f"[{self.name}] {s.signal.name} {s.symbol} @ {s.entry_price:.4f} | "
                f"SL={s.stop_loss:.4f} TP={s.take_profit:.4f} | "
                f"Conf={s.confidence:.2f} R:R={s.risk_reward_ratio:.2f}"
            )
